name: Matrix
on: workflow_dispatch
jobs:
  matrix:
    strategy:
      matrix:                                             # マトリックスの定義
        os: [ubuntu-latest, windows-latest, macos-latest] # osプロパティの定義
    runs-on: ${{ matrix.os }}                             # osプロパティの参照
    steps:
      - run: echo "${RUNNER_OS}"
        shell: bash
  multi-dim-matrix:
    strategy:
      matrix:                                 # 多次元マトリックスの定義
        os: [ubuntu-latest, macos-latest]     # osプロパティの定義
        version: [18, 20]                     # versionプロパティの定義
    runs-on: ${{ matrix.os }}                 # osプロパティの参照
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }} # versionプロパティの参照
      - run: echo "${RUNNER_OS}" && node --version
